### ISSUE TITLE
Error: Package name "LINEDIT-SCRATCH" is already in use.

### ISSUE THREAD

**Issue by RyanHope** [nikodemus/linedit#3]
I have issues with "linedit" on CCL 1.8. The problem happens when an error occurs. Here is an example:

> ? )

> Error: Reader error on #<STRING-INPUT-STREAM  #x3020012B1F9D>, near position 1, within ")":
>        Unmatched ')' .
> While executing: CCL::SIGNAL-READER-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > :POP

> Error: Package name "LINEDIT-SCRATCH" is already in use.
> While executing: MAKE-PACKAGE, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
> 2 >

**Comment by nikodemus** [comment]
Should be fixed. Please repoen this issue if not.
