### ISSUE TITLE
Installing with a space in the path fails

### ISSUE THREAD

**Issue by eschaton** [nikodemus/linedit#4]
Using trunk CCL on OS X 10.10, I'm trying and failing to install `linedit` via `quicklisp` on OS X, where my user directory is on a volume with a space in the path. (Specifically, the path to `~` is `/Volumes/Macintosh HD2/Users/cmh`.) It's failing to build `terminal_glue` because the compilation command it's generating isn't properly escaping the paths.

Here's the generated error:

    ? (ql:quickload "linedit")
    To load "linedit":
      Load 1 ASDF system:
        linedit
    ; Loading "linedit"
    > Error: OPERATION-ERROR while invoking #<COMPILE-OP > on #<UFFI-C-SOURCE-FILE "linedit" "terminal_glue">
    > While executing: #<STANDARD-METHOD ASDF/ACTION:PERFORM (ASDF/LISP-ACTION:COMPILE-OP LINEDIT-SYSTEM::UFFI-C-SOURCE-FILE)>, in process listener(1).
    > Type :POP to abort, :R for a list of available restarts.
    > Type :? for other options.

Editing `dists/quicklisp/software/linedit-20120703-git/linedit.asd` in my QuickLisp directory to use `~S` instead of `~A` works.

**Comment by nikodemus** [comment]
Hopefully fixed. Can you verify if current head works for you?

**Comment by eschaton** [comment]
I'll give it a try when it's next picked up in QuickLisp. Since this is basically the change I made to get it working on my system, I suspect it'll be fine.
