### ISSUE TITLE
Couldn't change highlighting color of parentheses.

### ISSUE THREAD

**Issue by algerbo** [nikodemus/linedit#5]
"Linedit" was installed through Quicklisp. (linedit-20120703-git)

In my ~/.sbclrc
--- cut--
```lisp
(when (find-package 'linedit)
 (setf linedit:*highlight-color* :red))
```
Got error:
```bash
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {B3E9201}>:
  Conditional expression parser not yet written.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

((FLET #:CLEANUP-FUN-25 :IN LINEDIT:LINEDIT)) [cleanup]
0]
```
When I tried set color manually after linedit was loaded I've got the same error.
```bash
CL-USER(1): (setf linedit:*highlight-color* :red)

:RED

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {B3E9201}>:
  Conditional expression parser not yet written.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

((FLET #:CLEANUP-FUN-25 :IN LINEDIT:LINEDIT)) [cleanup]
```
Have tested configuration from : https://github.com/0/.../blob/master/sbclrc
Result: Error was the same.

---
Linedit version 0.17.5
SBCL version 1.2.3.62-989a1d6

**Comment by nikodemus** [comment]
This seems a terminfo bug. (terminfo.lisp, that is)

Can you try replacing terminfo.lisp in Linedit with one from https://github.com/npatrick04/terminfo ?

Does the same error still occur?

**Comment by algerbo** [comment]
You are right! When I take terminfo.lisp from https://github.com/npatrick04/terminfo repository the error disappears and (setf linedit:*highlight-color* :red) working perfect. 
Will you do "merge" terminfo files without bugs ?

**Comment by nikodemus** [comment]
Fantastic, thanks! I don't actually have a box where I could reasonably test linedit accessible right now, but if you can verify that the test branch:

    https://github.com/nikodemus/linedit/tree/test

works, I'll be happy to update the master to that.

**Comment by algerbo** [comment]
I tried to install "tree/test" branch: "terminal and colorize functionality" works fine.
You did an excellent job, THUNX sir Nikodemus!

**Comment by nikodemus** [comment]
Thanks, on master now.
